#!/bin/bash

docker run -d --rm --name=deshette -p 8080:8080 --mount type=bind,source="$(pwd)"/deshette,target=/var/www/localhost/htdocs/wp-content/themes/deshette  --mount type=bind,source="$(pwd)"/deshette-react/dist,target=/var/www/localhost/htdocs/wp-content/themes/deshette-react aikidojohn/deshette:latest
